server:
  port: 8085
spring:
  application:
    name: microservice-customer

  jackson:
    serialization.write_dates_as_timestamps: false

  datasource:
    password: 'postgres'
    url: jdbc:postgresql://localhost:5432/customer
    username: 'postgres'
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true